# configs/model/regression.yaml

_target_: src.models.regression_module.RegressionLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 117
  lin1_size: 64
  lin2_size: 32
  lin3_size: 16
  output_size: 1

criterion:
  _target_: torch.nn.MSELoss # 可以轻易换成 torch.nn.L1Loss, etc.

